/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async function (knex) {
  // Deletes ALL existing entries
  await knex("activity").del();
  await knex("activity").insert([
    { user_id: 1, name: "Money", description: "I raised $200,000 for the USSF" },
    { user_id: 1, name: "Time", description: "I saved 3600 man-hours for the USSF by creating a new product" },
    { user_id: 1, name: "Mission", description: "I trained 72 guardians on mission products" },
    { user_id: 2, name: "Acq", description: "I worked on a 2M project" },
    { user_id: 2, name: "Mission", description: "I've supervised 327 successful missions for our unit." },
    { user_id: 2, name: "Training", description: "I took 12 trainings that will benefit the unit" },
    { user_id: 3, name: "Operations", description: "I was a crew commander for 1 SPAFORGEN cycle" },
    { user_id: 3, name: "Operations", description: "I was a crew commander for 1 SPAFORGEN cycle" },
    { user_id: 3, name: "Operations", description: "I was a crew commander for 1 SPAFORGEN cycle" },
    { user_id: 4, name: "Things", description: "I do stuff and things like 100 times a day" },
    { user_id: 4, name: "Things", description: "I do stuff and things like 100 times a day" },
    { user_id: 4, name: "Things", description: "I do stuff and things like 100 times a day" },
    { user_id: 5, name: "Stuff",  description: "I do stuff and things like 600 times a day" },
    { user_id: 6, name: "Lethal", description: "I am so lethal omg" },
    { user_id: 7, name: "Money", description: "There's a lot of money and I intend to get all of it" },
    { user_id: 8, name: "Rizzler", description: "My rizz has been insane lately..." },
    { user_id: 8, name: "Supervisor", description: "Did some paperwork type things" },
    { user_id: 8, name: "Instruction", description: "Showed 46 individuals how to do something" },
    { user_id: 1, name: "Fundraising", description: "Organized a charity event that raised $150,000 for USSF morale programs." },
    { user_id: 1, name: "Efficiency", description: "Developed an automated reporting tool, saving an estimated 2500 man-hours annually for the unit." },
    { user_id: 1, name: "Training", description: "Led three training sessions on advanced satellite communication systems for a total of 45 guardians." },
    { user_id: 1, name: "Project Management", description: "Successfully managed the deployment of a $1.2M upgrade to the ground control station." },
    { user_id: 1, name: "Innovation", description: "Proposed and prototyped a new method for space debris tracking, showing a potential 10% increase in accuracy." },
    { user_id: 2, name: "Acquisition", description: "Contributed to the successful negotiation of a $3.5M contract for new sensor technology." },
    { user_id: 2, name: "Process Improvement", description: "Identified and resolved a bottleneck in the data analysis pipeline, reducing processing time by 20%." },
    { user_id: 2, name: "Collaboration", description: "Facilitated a joint working group with Space Force and Air Force personnel to standardize data sharing protocols." },
    { user_id: 2, name: "Mentorship", description: "Provided mentorship to four junior guardians, resulting in improved performance evaluations." },
    { user_id: 3, name: "Cybersecurity", description: "Identified and mitigated three high-risk vulnerabilities in the unit's network infrastructure." },
    { user_id: 3, name: "Team Leadership", description: "Led a team of five guardians in the successful completion of a complex software upgrade project." },
    { user_id: 3, name: "Resource Management", description: "Effectively managed a budget of $500,000 for the procurement of new equipment." },
    { user_id: 3, name: "Strategic Planning", description: "Contributed to the development of the unit's five-year strategic plan, focusing on future technology integration." },
    { user_id: 4, name: "Data Analysis", description: "Conducted in-depth analysis of satellite telemetry data, identifying a potential anomaly in the [Fictional Subsystem]." },
    { user_id: 4, name: "Software Development", description: "Developed a new software application to automate the processing of [Fictional Data Type], improving efficiency." },
    { user_id: 4, name: "Problem Solving", description: "Successfully troubleshot and resolved a complex hardware malfunction in the [Fictional Equipment]." },
    { user_id: 5, name: "Outreach", description: "Represented the USSF at a STEM event, inspiring 32 students to consider careers in space." },
    { user_id: 5, name: "Safety", description: "Identified and implemented a new safety protocol in the Ops center, reducing the risk of accidents." },
    { user_id: 5, name: "Logistics", description: "Managed the successful deployment of critical supplies to the [Fictional Location] under a tight deadline." },
    { user_id: 5, name: "Community Building", description: "Organized a team-building event that improved morale and cohesion within the unit." },
    { user_id: 5, name: "Public Relations", description: "Developed content for the unit's social media platforms, increasing public awareness of their mission." },
    { user_id: 6, name: "Innovation", description: "Developed a proof-of-concept for using AI in Launch, showing promising results." },
    { user_id: 6, name: "Cost Savings", description: "Identified and implemented a cost-saving measure in the pipeline, saving the USSF an estimated $300K annually." },
    { user_id: 6, name: "Cross-functional Teamwork", description: "Effectively collaborated with members from three different squadrons to achieve a common objective." },
    { user_id: 6, name: "Data Visualization", description: "Created interactive dashboards to better visualize key performance indicators for the unit's leadership." },
    { user_id: 6, name: "Continuous Improvement", description: "Led a Kaizen event focused on improving the efficiency of the workflows, resulting in a 120% improvement." },
    { user_id: 7, name: "Training Development", description: "Developed a new curriculum for an advanced training program, enhancing guardian proficiency in a key area." },
    { user_id: 7, name: "Equipment Maintenance", description: "Led a team in the preventative maintenance of critical operational equipment, ensuring readiness." },
    { user_id: 7, name: "Security Protocol", description: "Revised and updated the security protocols for a sensitive area, improving overall safety and compliance." },
    { user_id: 7, name: "Knowledge Sharing", description: "Conducted several knowledge-sharing sessions on a complex technical topic for junior team members." },
    { user_id: 7, name: "Process Optimization", description: "Analyzed an administrative process and implemented changes that reduced processing time significantly." },
    { user_id: 8, name: "Interagency Coordination", description: "Successfully coordinated with personnel from a partner agency on a joint project related to a specific operational domain." },
    { user_id: 8, name: "Resource Allocation", description: "Managed the allocation of resources for a key project, ensuring efficient utilization of budget and personnel." },
    { user_id: 8, name: "Risk Management", description: "Identified and assessed potential risks associated with a major operation and developed mitigation strategies." },
    { user_id: 8, name: "System Integration", description: "Played a key role in the seamless integration of a new system into the existing infrastructure." },
    { user_id: 8, name: "Technical Support", description: "Provided expert technical support to resolve a critical issue with a software application affecting multiple users." },
  ]);
};
