/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async function (knex) {
  // Deletes ALL existing entries
  await knex("bullet").del();
  await knex("bullet").insert([
  {
    user_id: 1,
    name: "Space Operations",
    action: "Resolved anomaly on a critical navigation system",
    impact: "Restored mission-essential capabilities ahead of schedule",
    result: "Prevented potential data loss impacting multiple strategic missions",
    status: "Drafting",
    drafting: true,
    award_id: 1,
  },
  {
    user_id: 1,
    name: "Safety",
    action: "Executed debris avoidance maneuver for an orbiting asset",
    impact: "Ensured zero probability of collision",
    result: "Safeguarded significant space assets",
    status: "Supervisor Review",
    drafting: false,
    award_id: 3,
  },
  {
    user_id: 1,
    name: "Cybersecurity",
    action: "Identified and patched a critical vulnerability in a key software application",
    impact: "Prevented potential system compromise",
    result: "Safeguarded sensitive data and ensured operational continuity",
    status: "Drafting",
    drafting: true,
    award_id: 4,
  },
  {
    user_id: 1,
    name: "Process Improvement",
    action: "Streamlined a resource allocation process for ground operations",
    impact: "Improved efficiency",
    result: "Reduced resource expenditure and accelerated task completion",
    status: "Supervisor Review",
    drafting: false,
    award_id: 2,
  },
  {
    user_id: 1,
    name: "Cybersecurity",
    action: "Developed and implemented enhanced security protocols for a critical network",
    impact: "Strengthened overall cyber defense posture",
    result: "Mitigated multiple potential cyber threats",
    status: "Drafting",
    drafting: false,
    award_id: 4,
  },
  {
    user_id: 2,
    name: "Safety",
    action: "Executed debris avoidance maneuver for an orbiting asset",
    impact: "Ensured zero probability of collision",
    result: "Safeguarded significant space assets",
    status: "Supervisor Review",
    drafting: false,
    award_id: 3,
  },
  {
    user_id: 2,
    name: "Ground Operations",
    action: "Mitigated a cyber vulnerability in a mission control system",
    impact: "Restored mission-essential capabilities ahead of schedule",
    result:
      "Prevented potential unauthorized access to sensitive intelligence",
    status: "Supervisor Review",
    drafting: false,
    award_id: 2,
  },
  {
    user_id: 2,
    name: "Cybersecurity",
    action: "Developed and implemented enhanced security protocols for a critical network",
    impact: "Strengthened overall cyber defense posture",
    result: "Mitigated multiple potential cyber threats",
    status: "Drafting",
    drafting: true,
    award_id: 4,
  },
  {
    user_id: 2,
    name: "Space Operations",
    action: "Successfully recovered from a critical failure in a spacecraft subsystem",
    impact: "Minimized mission downtime",
    result: "Preserved critical data collection capabilities",
    status: "Drafting",
    drafting: true,
    award_id: 1,
  },
  {
    user_id: 2,
    name: "Cybersecurity",
    action: "Conducted proactive threat hunting on a key operational system",
    impact: "Identified and neutralized potential indicators of compromise",
    result: "Prevented potential data breach and system disruption",
    status: "Supervisor Review",
    drafting: false,
    award_id: 4,
  },
  {
    user_id: 3,
    name: "Ground Operations",
    action: "Mitigated a cyber vulnerability in a mission control system",
    impact: "Restored mission-essential capabilities ahead of schedule",
    result:
      "Prevented potential unauthorized access to sensitive intelligence",
    status: "Supervisor Review",
    drafting: false,
    award_id: 2,
  },
  {
    user_id: 3,
    name: "Space Operations",
    action: "Resolved anomaly on a critical navigation system",
    impact: "Restored mission-essential capabilities ahead of schedule",
    result: "Prevented potential data loss impacting multiple strategic missions",
    status: "Drafting",
    drafting: true,
    award_id: 1,
  },
  {
    user_id: 3,
    name: "Operational Support",
    action: "Led integration efforts for a new operational capability",
    impact: "Achieved seamless operational transition",
    result: "Enhanced mission effectiveness and responsiveness",
    status: "Awarded",
    drafting: false,
    award_id: 1,
  },
  {
    user_id: 3,
    name: "Cybersecurity",
    action: "Conducted proactive threat hunting on a key operational system",
    impact: "Identified and neutralized potential indicators of compromise",
    result: "Prevented potential data breach and system disruption",
    status: "Supervisor Review",
    drafting: false,
    award_id: 4,
  },
  {
    user_id: 3,
    name: "Cybersecurity",
    action: "Authored comprehensive cybersecurity training module on a key security topic",
    impact: "Improved user awareness and adherence to security best practices",
    result: "Reduced the risk of insider threats",
    status: "Drafting",
    drafting: true,
    award_id: 4,
  },
  {
    user_id: 4,
    name: "Operational Support",
    action: "Aided deployment of a new technology",
    impact: "Achieved all performance metrics",
    result: "Accelerated fielding of enhanced space capabilities",
    status: "Awarded",
    drafting: false,
    award_id: 1,
  },
  {
    user_id: 4,
    name: "Space Operations",
    action: "Performed a critical space operations duty during an exercise",
    impact: "Demonstrated exceptional awareness",
    result: "Flawlessly executed mission objectives",
    status: "Supervisor Approved",
    drafting: false,
    award_id: 2,
  },
  {
    user_id: 4,
    name: "Safety",
    action: "Provided critical real-time support during a contingency event",
    impact: "Ensured accurate and timely information flow",
    result: "Facilitated effective decision-making and resource allocation",
    status: "Awarded",
    drafting: false,
    award_id: 3,
  },
  {
    user_id: 4,
    name: "Cybersecurity",
    action: "Authored comprehensive cybersecurity training module on a key security topic",
    impact: "Improved user awareness and adherence to security best practices",
    result: "Reduced the risk of insider threats",
    status: "Drafting",
    drafting: true,
    award_id: 4,
  },
  {
    user_id: 4,
    name: "Cybersecurity",
    action: "Performed security audit of a system configuration",
    impact: "Identified and corrected multiple misconfigurations",
    result: "Strengthened the system's security posture against known vulnerabilities",
    status: "Drafting",
    drafting: true,
    award_id: 4,
  },
  {
    user_id: 5,
    name: "Space Operations",
    action: "Performed a critical space operations duty during an exercise",
    impact: "Demonstrated exceptional awareness",
    result: "Flawlessly executed mission objectives",
    status: "Supervisor Approved",
    drafting: false,
    award_id: 2,
  },
  {
    user_id: 5,
    name: "Leadership",
    action: "Led a team of guardians",
    impact: "Fostered cohesive, high-performing unit",
    result: "Consistently achieved mission objectives under pressure",
    status: "Awarded",
    drafting: false,
    award_id: 1,
  },
  {
    user_id: 5,
    name: "Innovation",
    action: "Developed an innovative solution for a spacecraft issue",
    impact: "Improved system performance",
    result: "Extended the operational lifespan of a critical asset",
    status: "Awarded",
    drafting: false,
    award_id: 1,
  },
  {
    user_id: 5,
    name: "Cybersecurity",
    action: "Performed security audit of a system configuration",
    impact: "Identified and corrected multiple misconfigurations",
    result: "Strengthened the system's security posture against known vulnerabilities",
    status: "Drafting",
    drafting: true,
    award_id: 4,
  },
  {
    user_id: 5,
    name: "Ground Operations",
    action: "Troubleshot and resolved a complex issue with ground equipment",
    impact: "Restored critical ground segment functionality",
    result: "Prevented mission delays and data loss",
    status: "Supervisor Approved",
    drafting: false,
    award_id: 2,
  },
  {
    user_id: 6,
    name: "Training",
    action: "Developed training for a space domain task",
    impact: "Increased team proficiency",
    result: "Reduced mission execution timelines",
    status: "Awarded",
    drafting: false,
    award_id: 1,
  },
  {
    user_id: 6,
    name: "Mentorship",
    action: "Mentored junior team members on advanced systems",
    impact: "Enhanced team capabilities and knowledge base",
    result: "Improved overall team performance and effectiveness",
    status: "Supervisor Approved",
    drafting: false,
    award_id: 3,
  },
  {
    user_id: 6,
    name: "Ground Operations",
    action: "Led the upgrade of a satellite communication component",
    impact: "Increased system reliability and processing speed",
    result: "Improved data analysis capabilities for mission support",
    status: "Awarded",
    drafting: false,
    award_id: 2,
  },
  {
    user_id: 6,
    name: "Cybersecurity",
    action: "Conducted a comprehensive vulnerability assessment of a software application",
    impact: "Identified critical security flaws",
    result: "Enabled timely remediation efforts",
    status: "Drafting",
    drafting: true,
    award_id: 4,
  },
  {
    user_id: 6,
    name: "Cybersecurity",
    action: "Responded to and contained a significant cyber incident",
    impact: "Minimized damage and prevented further exploitation",
    result: "Ensured the integrity and availability of critical systems",
    status: "Drafting",
    drafting: true,
    award_id: 4,
  },
  {
    user_id: 7,
    name: "Ground Operations",
    action: "Developed automated scripts for routine system checks",
    impact: "Reduced manual effort",
    result: "Freed up personnel for higher-priority tasks and reduced error rate",
    status: "Awarded",
    drafting: false,
    award_id: 2,
  },
  {
    user_id: 7,
    name: "Logistics",
    action: "Coordinated logistics for a critical resupply mission",
    impact: "Ensured timely and efficient resource delivery",
    result: "Contributed directly to the successful execution of the operation",
    status: "Supervisor Review",
    drafting: false,
    award_id: 3,
  },
  {
    user_id: 7,
    name: "Cybersecurity",
    action: "Responded to and contained a Distributed Denial of Service attack",
    impact: "Minimized damage and prevented further exploitation",
    result: "Ensured the integrity and availability of critical systems",
    status: "Drafting",
    drafting: true,
    award_id: 4,
  },
  {
    user_id: 7,
    name: "Training Development",
    action: "Developed a new curriculum for an advanced training program",
    impact: "Enhanced guardian proficiency",
    result: "Improved overall operational effectiveness",
    status: "Awarded",
    drafting: false,
    award_id: 1,
  },
  {
    user_id: 7,
    name: "Cybersecurity",
    action: "Implemented enhanced security measures for a sensitive area",
    impact: "Strengthened protection against potential threats",
    result: "Improved overall security posture",
    status: "Drafting",
    drafting: true,
    award_id: 4,
  },
  {
    user_id: 8,
    name: "Volunteer Work",
    action: "Volunteered for an interagency project",
    impact: "Contributed significantly",
    result:
      "Improved inter-agency coordination beyond primary duties",
    status: "Supervisor Approved",
    drafting: false,
    award_id: 2,
  },
  {
    user_id: 8,
    name: "Leadership",
    action: "Led a team of guardians",
    impact: "Fostered cohesive, high-performing unit",
    result: "Consistently achieved mission objectives under pressure",
    status: "Awarded",
    drafting: false,
    award_id: 1,
  },
  {
    user_id: 8,
    name: "Training",
    action: "Developed training for a complex procedure",
    impact: "Increased team proficiency",
    result: "Reduced mission execution timelines",
    status: "Awarded",
    drafting: false,
    award_id: 1,
  },
  {
    user_id: 8,
    name: "Space Operations",
    action: "Resolved anomaly on a critical navigation system",
    impact: "Restored mission-essential capabilities ahead of schedule",
    result: "Prevented potential data loss impacting multiple strategic missions",
    status: "Supervisor Approved",
    drafting: false,
    award_id: 1,
  },
  {
    user_id: 8,
    name: "Cybersecurity",
    action: "Developed a new training curriculum for a key security technology",
    impact: "Improved operator proficiency and reduced training time",
    result: "Enhanced overall operational effectiveness",
    status: "Supervisor Review",
    drafting: false,
    award_id: 4,
  },
  ]);
};
